// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ReadFile(arg1) {
  return window['go']['main']['App']['ReadFile'](arg1);
}

export function ReadSettings() {
  return window['go']['main']['App']['ReadSettings']();
}

export function Request(arg1) {
  return window['go']['main']['App']['Request'](arg1);
}

export function SelectImage() {
  return window['go']['main']['App']['SelectImage']();
}

export function WriteSettings(arg1) {
  return window['go']['main']['App']['WriteSettings'](arg1);
}
